# Generated by Django 4.2.1 on 2023-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SUser",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("username", models.TextField(max_length=20)),
                ("email", models.EmailField(max_length=75)),
                ("password", models.CharField(max_length=8)),
            ],
        ),
    ]
